### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Lykr** [v2rayA/v2rayA#1027]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
2.1.2

3. What approach of installation do you install V2rayA?
docker-compose

4. What is your operating system?
ubuntu

### Description

The v2rayA container failed to startup due to accessing invalid memory address or nil pointer issue.

### Steps to reproduce

Run following command to start v2raya:

```shell
sudo docker-compose up
```

The configuration of v2raya in docker-compose.yaml:

```yaml
  v2raya:
    # :2017
    container_name: v2raya
    image: "mzz2017/v2raya"
    environment:
      - V2RAYA_ADDRESS=0.0.0.0:2017
    volumes:
      - /lib/modules:/lib/modules:ro
      - /etc/resolv.conf:/etc/resolv.conf
      - /etc/v2raya:/etc/v2raya
    restart: always
    privileged: true
    network_mode: host
```

### Logs：

```log
2023/08/13 05:12:08.599 [A] [main.go:28]  V2Ray binary is /usr/bin/v2ray
2023/08/13 05:12:08.599 [A] [main.go:28]  V2Ray asset directory is /run/user/0/v2raya
2023/08/13 05:12:08.599 [A] [main.go:28]  v2rayA working directory is /root
2023/08/13 05:12:08.599 [A] [main.go:28]  v2rayA configuration directory is /etc/v2raya
2023/08/13 05:12:08.599 [A] [main.go:28]  Golang: go1.21.0
2023/08/13 05:12:08.599 [A] [main.go:28]  OS: linux
2023/08/13 05:12:08.599 [A] [main.go:28]  Arch: amd64
2023/08/13 05:12:08.599 [A] [main.go:28]  Lite: false
2023/08/13 05:12:08.599 [A] [main.go:28]  Version: 2.1.2
2023/08/13 05:12:08.599 [A] [main.go:28]  Starting...
2023/08/13 05:12:08.620 [I] [io.go:432]  V2Ray 5.4.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.2 linux/amd64)
2023/08/13 05:12:08.620 [I] [io.go:432]  A unified platform for anti-censorship.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xbb415c]

goroutine 148 [running]:
github.com/v2fly/v2ray-core/v5/common/strmatcher.(*DomainMatcherGroup).AddDomainMatcher(0xc000880000?, {0xc00019e0ca, 0x2}, 0x1)
        /go/pkg/mod/github.com/v2fly/v2ray-core/v5@v5.7.0/common/strmatcher/matchergroup_domain.go:38 +0xbc
github.com/v2rayA/v2rayA/core/specialMode/infra.(*DomainMatcherGroup).Add(...)
        /build/service/core/specialMode/infra/matcher.go:20
github.com/v2rayA/v2rayA/core/specialMode/infra.GetWhitelistCn({0x0, 0x0, 0xc00055fe56?})
        /build/service/core/specialMode/infra/whitelistcn.go:48 +0x805
github.com/v2rayA/v2rayA/core/specialMode.StartDNSSupervisor.func2.2()
        /build/service/core/specialMode/supervisor_linux.go:120 +0x46a
github.com/v2rayA/v2rayA/core/specialMode.StartDNSSupervisor.func2(0x1da98e0)
        /build/service/core/specialMode/supervisor_linux.go:146 +0x8f
created by github.com/v2rayA/v2rayA/core/specialMode.StartDNSSupervisor in goroutine 1
        /build/service/core/specialMode/supervisor_linux.go:77 +0x245
```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by Lykr** [comment]
Close this issue since this issue was gone after updating the image to 2.1.3.
