### ISSUE TITLE
将 v2raya 和 v2ray 分别更新至 v2raya 2.1.2 和 v2ray 5.7.0 后无法启动

### ISSUE THREAD

**Issue by XDwanj** [v2rayA/v2rayA#1028]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

`v2raya 2.1.2` 和 `v2ray 5.7.0`

2. 你通过什么方式安装v2rayA

通过 manjaro 包管理工具，`yay -S v2raya v2ray`

3. 你所使用的操作系统

```
OS: Manjaro Linux x86_64 
Host: 82B6 Lenovo Legion R70002020 
Kernel: 6.1.44-1-MANJARO 
Uptime: 30 mins 
Packages: 1882 (pacman) 
Shell: zsh 5.9 
Resolution: 1920x1080 
DE: GNOME 44.3 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adw-dark [GTK2/3] 
Icons: Papirus-Dark-Maia [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 7 4800H with Radeon Graphics (16)
GPU: NVIDIA GeForce GTX 1650 Ti Mobile 
Memory: 8026MiB / 15864MiB 
```

### 描述问题：

将 v2raya 和 v2ray 分别更新至 `v2raya 2.1.2` 和 `v2ray 5.7.0` 后发现没有正常工作，于是 `sudo systemctl status v2raya` 发现 v2raya 没有正常启动，但是 v2ray-core 可以正常启动

### v2rayA运行日志（Optional）：

 ```bash
8月 13 14:57:44 Manjaro v2raya[47687]:         github.com/v2rayA/v2rayA/core/specialMode/supervisor_linux.go:146 +0x8f
8月 13 14:57:44 Manjaro v2raya[47687]: created by github.com/v2rayA/v2rayA/core/specialMode.StartDNSSupervisor in goroutine 1
8月 13 14:57:44 Manjaro v2raya[47687]:         github.com/v2rayA/v2rayA/core/specialMode/supervisor_linux.go:77 +0x245
8月 13 14:57:44 Manjaro systemd[1]: v2raya.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
8月 13 14:57:44 Manjaro systemd[1]: v2raya.service: Failed with result 'exit-code'.
8月 13 14:57:45 Manjaro systemd[1]: v2raya.service: Scheduled restart job, restart counter is at 3.
8月 13 14:57:45 Manjaro systemd[1]: Stopped v2rayA Service.
8月 13 14:57:45 Manjaro systemd[1]: Started v2rayA Service.
8月 13 14:57:46 Manjaro v2raya[47954]: panic: runtime error: invalid memory address or nil pointer dereference
8月 13 14:57:46 Manjaro v2raya[47954]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x55c8d158a3fc]
8月 13 14:57:46 Manjaro v2raya[47954]: goroutine 217 [running]:
8月 13 14:57:46 Manjaro v2raya[47954]: github.com/v2fly/v2ray-core/v5/common/strmatcher.(*DomainMatcherGroup).AddDomainMatcher(0xc000c00000?, {0xc000a9f47a, 0x2}, 0x1)
8月 13 14:57:46 Manjaro v2raya[47954]:         github.com/v2fly/v2ray-core/v5@v5.7.0/common/strmatcher/matchergroup_domain.go:38 +0xbc
8月 13 14:57:46 Manjaro v2raya[47954]: github.com/v2rayA/v2rayA/core/specialMode/infra.(*DomainMatcherGroup).Add(...)
8月 13 14:57:46 Manjaro v2raya[47954]:         github.com/v2rayA/v2rayA/core/specialMode/infra/matcher.go:20
8月 13 14:57:46 Manjaro v2raya[47954]: github.com/v2rayA/v2rayA/core/specialMode/infra.GetWhitelistCn({0x0, 0x0, 0xc0008b77ec?})
8月 13 14:57:46 Manjaro v2raya[47954]:         github.com/v2rayA/v2rayA/core/specialMode/infra/whitelistcn.go:48 +0x805
8月 13 14:57:46 Manjaro v2raya[47954]: github.com/v2rayA/v2rayA/core/specialMode.StartDNSSupervisor.func2.2()
8月 13 14:57:46 Manjaro v2raya[47954]:         github.com/v2rayA/v2rayA/core/specialMode/supervisor_linux.go:120 +0x46a
8月 13 14:57:46 Manjaro v2raya[47954]: github.com/v2rayA/v2rayA/core/specialMode.StartDNSSupervisor.func2(0x55c8d27330e0)
8月 13 14:57:46 Manjaro v2raya[47954]:         github.com/v2rayA/v2rayA/core/specialMode/supervisor_linux.go:146 +0x8f
8月 13 14:57:46 Manjaro v2raya[47954]: created by github.com/v2rayA/v2rayA/core/specialMode.StartDNSSupervisor in goroutine 1
8月 13 14:57:46 Manjaro v2raya[47954]:         github.com/v2rayA/v2rayA/core/specialMode/supervisor_linux.go:77 +0x245
8月 13 14:57:46 Manjaro systemd[1]: v2raya.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
8月 13 14:57:46 Manjaro systemd[1]: v2raya.service: Failed with result 'exit-code'.
8月 13 14:57:46 Manjaro systemd[1]: v2raya.service: Scheduled restart job, restart counter is at 4.
8月 13 14:57:46 Manjaro systemd[1]: Stopped v2rayA Service.
8月 13 14:57:46 Manjaro systemd[1]: Started v2rayA Service.
8月 13 14:57:47 Manjaro v2raya[48222]: panic: runtime error: invalid memory address or nil pointer dereference
8月 13 14:57:47 Manjaro v2raya[48222]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5637ab2783fc]
8月 13 14:57:47 Manjaro v2raya[48222]: goroutine 282 [running]:
8月 13 14:57:47 Manjaro v2raya[48222]: github.com/v2fly/v2ray-core/v5/common/strmatcher.(*DomainMatcherGroup).AddDomainMatcher(0xc000d00000?, {0xc000ad331a, 0x2}, 0x1)
8月 13 14:57:47 Manjaro v2raya[48222]:         github.com/v2fly/v2ray-core/v5@v5.7.0/common/strmatcher/matchergroup_domain.go:38 +0xbc
8月 13 14:57:47 Manjaro v2raya[48222]: github.com/v2rayA/v2rayA/core/specialMode/infra.(*DomainMatcherGroup).Add(...)
8月 13 14:57:47 Manjaro v2raya[48222]:         github.com/v2rayA/v2rayA/core/specialMode/infra/matcher.go:20
8月 13 14:57:47 Manjaro v2raya[48222]: github.com/v2rayA/v2rayA/core/specialMode/infra.GetWhitelistCn({0x0, 0x0, 0xc00046f9cc?})
8月 13 14:57:47 Manjaro v2raya[48222]:         github.com/v2rayA/v2rayA/core/specialMode/infra/whitelistcn.go:48 +0x805
8月 13 14:57:47 Manjaro v2raya[48222]: github.com/v2rayA/v2rayA/core/specialMode.StartDNSSupervisor.func2.2()
8月 13 14:57:47 Manjaro v2raya[48222]:         github.com/v2rayA/v2rayA/core/specialMode/supervisor_linux.go:120 +0x46a
8月 13 14:57:47 Manjaro v2raya[48222]: github.com/v2rayA/v2rayA/core/specialMode.StartDNSSupervisor.func2(0x5637ac4210e0)
8月 13 14:57:47 Manjaro v2raya[48222]:         github.com/v2rayA/v2rayA/core/specialMode/supervisor_linux.go:146 +0x8f
8月 13 14:57:47 Manjaro v2raya[48222]: created by github.com/v2rayA/v2rayA/core/specialMode.StartDNSSupervisor in goroutine 1
8月 13 14:57:47 Manjaro v2raya[48222]:         github.com/v2rayA/v2rayA/core/specialMode/supervisor_linux.go:77 +0x245
8月 13 14:57:47 Manjaro systemd[1]: v2raya.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
8月 13 14:57:47 Manjaro systemd[1]: v2raya.service: Failed with result 'exit-code'.
8月 13 14:57:47 Manjaro systemd[1]: v2raya.service: Scheduled restart job, restart counter is at 5.
8月 13 14:57:47 Manjaro systemd[1]: Stopped v2rayA Service.
8月 13 14:57:47 Manjaro systemd[1]: v2raya.service: Start request repeated too quickly.
8月 13 14:57:47 Manjaro systemd[1]: v2raya.service: Failed with result 'exit-code'.
8月 13 14:57:47 Manjaro systemd[1]: Failed to start v2rayA Service.
 ```

```
$ sudo systemctl status v2raya
× v2raya.service - v2rayA Service
     Loaded: loaded (/usr/lib/systemd/system/v2raya.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Sun 2023-08-13 14:57:47 CST; 14min ago
   Duration: 1.102s
       Docs: https://github.com/v2rayA/v2rayA/wiki
    Process: 48222 ExecStart=/usr/bin/v2raya --log-disable-timestamp (code=exited, status=2)
   Main PID: 48222 (code=exited, status=2)

8月 13 14:57:47 Manjaro systemd[1]: v2raya.service: Scheduled restart job, restart counter is at 5.
8月 13 14:57:47 Manjaro systemd[1]: Stopped v2rayA Service.
8月 13 14:57:47 Manjaro systemd[1]: v2raya.service: Start request repeated too quickly.
8月 13 14:57:47 Manjaro systemd[1]: v2raya.service: Failed with result 'exit-code'.
8月 13 14:57:47 Manjaro systemd[1]: Failed to start v2rayA Service.
```

```
$ sudo systemctl status v2ray
● v2ray.service - V2Ray Service
     Loaded: loaded (/usr/lib/systemd/system/v2ray.service; enabled; preset: disabled)
     Active: active (running) since Sun 2023-08-13 14:57:41 CST; 12min ago
       Docs: https://www.v2fly.org/
   Main PID: 47114 (v2ray)
      Tasks: 20 (limit: 19011)
     Memory: 38.2M
     CGroup: /system.slice/v2ray.service
             └─47114 /usr/bin/v2ray run -config /etc/v2ray/config.json

8月 13 14:57:41 Manjaro systemd[1]: Started V2Ray Service.
8月 13 14:57:41 Manjaro v2ray[47114]: V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.4 linux/amd64)
8月 13 14:57:41 Manjaro v2ray[47114]: A unified platform for anti-censorship.
8月 13 14:57:41 Manjaro v2ray[47114]: 2023/08/13 14:57:41 [Warning] V2Ray 5.7.0 started
```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

无法打开网页

**Comment by mzz2017** [comment]
再升一下，2.1.3解决了

**Comment by XDwanj** [comment]
> 再升一下，2.1.3解决了

感谢，问题解决了😄
