### ISSUE TITLE
友情提问——关于Java后端配置走v2ray代理

### ISSUE THREAD

**Issue by Buenbk** [v2rayA/v2rayA#1353]
### 版本、安装方式、系统
最新版v2rayA、Ubuntu20.04

### 描述问题：
我本地windows开发环境运行了vpn（HTTP33210，SOCKS33211），然后使用了以下配置成功地让Java后端通过代理访问Steam的社区api
```
private final RestTemplate restTemplate= new RestTemplateBuilder()
            .requestFactory(() -> {
                SimpleClientHttpRequestFactory requestFactory = new SimpleClientHttpRequestFactory();
                Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("localhost", 33210))
                requestFactory.setProxy(proxy);
                return requestFactory;
            }).build();
```
我的Ubuntu服务器使用了V2RayA来进行代理，并成功Ping通对应网址，然后我用以下配置企图同样让部署于Docker容器的Java后端走代理，但是失败了，报错显示connnection refused，与没有配置代理的错误是一样的，我想请问大佬知道Ubuntu的程序如果要走代理要怎么配置吗？
```
private final RestTemplate restTemplate= new RestTemplateBuilder()
                .requestFactory(() -> {
        SimpleClientHttpRequestFactory requestFactory = new SimpleClientHttpRequestFactory();
                    /*
                    ubuntu服务器的v2rayA的端口
                    20170: SOCKS协议
                    20171: HTTP协议
                    20172: 带分流规则的HTTP协议
                     */
        //Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("localhost", 20171));//尝试一
        //Proxy proxy = new Proxy(Proxy.Type.SOCKS, new InetSocketAddress("localhost", 20170));//尝试二
        Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("服务器ip地址", 20171));//尝试三
        //Proxy proxy = new Proxy(Proxy.Type.SOCKS, new InetSocketAddress("服务器ip地址", 20170));//尝试四
        requestFactory.setProxy(proxy);
        return requestFactory;
    }).build();
```

### v2rayA设置以及相关截图
v2rayA设置为安装后的**默认设置**，没有动过
![image](https://github.com/v2rayA/v2rayA/assets/82649417/715f0aad-04bb-492c-9c44-6c2293900730)
```
Connection refused; nested exception is java.net.ConnectException: Connection refused
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602)
```

**Comment by Buenbk** [comment]
![image](https://github.com/v2rayA/v2rayA/assets/82649417/baa0fb4e-f756-40c2-924e-c76e69441033)
开启了透明代理后，命令行突然无法ping通steamcommunity.com这个网址了
