### ISSUE TITLE
v2rayA 启动时 runtime error (SIGSEGV)

### ISSUE THREAD

**Issue by luosh18** [v2rayA/v2rayA#269]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
   1.5.3

2. 你通过什么方式安装v2rayA
   apt

3. 你所使用的操作系统
   Ubuntu 20.04 LTS, Linux kernel 5.13.13-051313-generic

### 描述问题

v2rayA 无法启动

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa36818]
```

### 复现问题的步骤

启动 v2raya

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志
9月 24 17:29:33 ubuntu-GA502IV v2raya[7607]:         /home/runner/work/v2rayA/v2rayA/service/core/v2ray/v2rayTmpl.go:1260 +0xd1b
9月 24 17:29:33 ubuntu-GA502IV v2raya[7607]: github.com/v2rayA/v2rayA/core/v2ray.NewTemplate({0xc00090b5c0, 0x1, 0x1}, 0x0)
9月 24 17:29:33 ubuntu-GA502IV v2raya[7607]:         /home/runner/work/v2rayA/v2rayA/service/core/v2ray/v2rayTmpl.go:1451 +0x48d
9月 24 17:29:33 ubuntu-GA502IV v2raya[7607]: github.com/v2rayA/v2rayA/core/v2ray.NewTemplateFromConnectedServers(0xafff80)
9月 24 17:29:33 ubuntu-GA502IV v2raya[7607]:         /home/runner/work/v2rayA/v2rayA/service/core/v2ray/process.go:250 +0xee
9月 24 17:29:33 ubuntu-GA502IV v2raya[7607]: github.com/v2rayA/v2rayA/core/v2ray.UpdateV2RayConfig()
9月 24 17:29:33 ubuntu-GA502IV v2raya[7607]:         /home/runner/work/v2rayA/v2rayA/service/core/v2ray/process.go:258 +0x1f
9月 24 17:29:33 ubuntu-GA502IV v2raya[7607]: main.run()
9月 24 17:29:33 ubuntu-GA502IV v2raya[7607]:         /home/runner/work/v2rayA/v2rayA/service/pre.go:379 +0x65
9月 24 17:29:33 ubuntu-GA502IV v2raya[7607]: main.main()
9月 24 17:29:33 ubuntu-GA502IV v2raya[7607]:         /home/runner/work/v2rayA/v2rayA/service/main.go:27 +0x79
9月 24 17:29:33 ubuntu-GA502IV systemd[1]: v2raya.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
9月 24 17:29:33 ubuntu-GA502IV systemd[1]: v2raya.service: Failed with result 'exit-code'.
9月 24 17:29:33 ubuntu-GA502IV systemd[1]: v2raya.service: Scheduled restart job, restart counter is at 4.
9月 24 17:29:33 ubuntu-GA502IV systemd[1]: Stopped v2rayA Service.
9月 24 17:29:33 ubuntu-GA502IV systemd[1]: Started v2rayA Service.
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: [A] [main.go:24]  network is connected
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: [A] [main.go:26]  V2RayLocationAsset is /usr/local/share/xray
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: [A] [main.go:26]  V2Ray binary is /usr/local/bin/xray
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: [A] [main.go:26]  v2rayA working directory is /
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: [A] [main.go:26]  v2rayA configuration directory is /etc/v2raya
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: [A] [main.go:26]  OS: linux
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: [A] [main.go:26]  Arch: amd64
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: [A] [main.go:26]  Lite: false
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: [A] [main.go:26]  Version: 1.5.3
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: [A] [main.go:26]  Starting...
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: panic: runtime error: invalid memory address or nil pointer dereference
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa36818]
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: goroutine 1 [running]:
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: github.com/v2rayA/v2rayA/core/serverObj.(*V2Ray).Configuration(0xc0004604b0, {{0xe5616c, 0xd}, {_, _}, _})
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]:         /home/runner/work/v2rayA/v2rayA/service/core/serverObj/v2ray.go:336 +0x1158
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: github.com/v2rayA/v2rayA/core/v2ray.(*Template).resolveOutbounds(0xc00058e240, 0xc0008b20a0)
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]:         /home/runner/work/v2rayA/v2rayA/service/core/v2ray/v2rayTmpl.go:1260 +0xd1b
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: github.com/v2rayA/v2rayA/core/v2ray.NewTemplate({0xc000812c30, 0x1, 0x1}, 0x0)
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]:         /home/runner/work/v2rayA/v2rayA/service/core/v2ray/v2rayTmpl.go:1451 +0x48d
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: github.com/v2rayA/v2rayA/core/v2ray.NewTemplateFromConnectedServers(0xafff80)
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]:         /home/runner/work/v2rayA/v2rayA/service/core/v2ray/process.go:250 +0xee
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: github.com/v2rayA/v2rayA/core/v2ray.UpdateV2RayConfig()
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]:         /home/runner/work/v2rayA/v2rayA/service/core/v2ray/process.go:258 +0x1f
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: main.run()
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]:         /home/runner/work/v2rayA/v2rayA/service/pre.go:379 +0x65
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]: main.main()
9月 24 17:29:33 ubuntu-GA502IV v2raya[7718]:         /home/runner/work/v2rayA/v2rayA/service/main.go:27 +0x79
9月 24 17:29:33 ubuntu-GA502IV systemd[1]: v2raya.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
9月 24 17:29:33 ubuntu-GA502IV systemd[1]: v2raya.service: Failed with result 'exit-code'.
9月 24 17:29:34 ubuntu-GA502IV systemd[1]: v2raya.service: Scheduled restart job, restart counter is at 5.
9月 24 17:29:34 ubuntu-GA502IV systemd[1]: Stopped v2rayA Service.
9月 24 17:29:34 ubuntu-GA502IV systemd[1]: v2raya.service: Start request repeated too quickly.
9月 24 17:29:34 ubuntu-GA502IV systemd[1]: v2raya.service: Failed with result 'exit-code'.
9月 24 17:29:34 ubuntu-GA502IV systemd[1]: Failed to start v2rayA Service.
```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
https://github.com/v2rayA/v2rayA/actions/runs/1269308055

已修，尝试使用该版本的二进制文件替换你的 v2raya。

**Comment by luosh18** [comment]
正常了，谢谢。

**Comment by mzz2017** [comment]
该 issue 将会关闭，因为该问题已在 v1.5.4 中修复。
