### ISSUE TITLE
golang panic

### ISSUE THREAD

**Issue by murez** [v2rayA/v2rayA#445]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?

1.5.6.2

2. What approach of installation do you install V2rayA?

linux x64 release binary

3. What is your operating system?

centos7

### Description

golang panic

### Logs：

```shell

V2RAYA_V2RAY_CONFDIR=/public/***/v2fly/ V2RAYA_V2RAY_BIN=/public/***/v2fly/v2ray V2RAYA_CONFIG=/public/***/v2raya/etc/v2raya/ ./v2raya --lite

...

2022/03/10 11:16:02.279 [I] [asm_amd64.s:1581]  down<geoip.dat> 11364738-11905915

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/v2rayA/v2rayA/core/v2ray/asset/dat.UpdateLocalGeoIP()
        /home/runner/work/v2rayA/v2rayA/service/core/v2ray/asset/dat/geoip.go:30 +0x3dc
main.initConfigure()
        /home/runner/work/v2rayA/v2rayA/service/pre.go:243 +0x437
main.main()
        /home/runner/work/v2rayA/v2rayA/service/main.go:25 +0x6a



```

`V2RAYA_CONFIG`'s content is copied from another linux machine's etc 

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by murez** [comment]
And could you please release a wiki with user only mode

**Comment by AprilGrimoire** [comment]
same problem
```
aprilgrimoire@aprilgrimoire-HLYL-WXX9:~$ v2raya --lite
2022/03/14 00:01:30.020 [A] [main.go:25]  network is connected
2022/03/14 00:01:32.605 [I] [asm_amd64.s:1581]  down<geoip.dat> 14205945-15153008

2022/03/14 00:01:32.605 [I] [asm_amd64.s:1581]  down<geoip.dat> 0-947062

2022/03/14 00:01:32.605 [I] [asm_amd64.s:1581]  down<geoip.dat> 12311819-13258881

2022/03/14 00:01:32.606 [I] [asm_amd64.s:1581]  down<geoip.dat> 3788252-4735314

2022/03/14 00:01:32.605 [I] [asm_amd64.s:1581]  down<geoip.dat> 6629441-7576503

2022/03/14 00:01:32.606 [I] [asm_amd64.s:1581]  down<geoip.dat> 4735315-5682377

2022/03/14 00:01:32.606 [I] [asm_amd64.s:1581]  down<geoip.dat> 11364756-12311818

2022/03/14 00:01:32.605 [I] [asm_amd64.s:1581]  down<geoip.dat> 5682378-6629440

2022/03/14 00:01:32.607 [I] [asm_amd64.s:1581]  down<geoip.dat> 947063-1894125

2022/03/14 00:01:32.607 [I] [asm_amd64.s:1581]  down<geoip.dat> 9470630-10417692

2022/03/14 00:01:32.607 [I] [asm_amd64.s:1581]  down<geoip.dat> 10417693-11364755

2022/03/14 00:01:32.607 [I] [asm_amd64.s:1581]  down<geoip.dat> 8523567-9470629

2022/03/14 00:01:32.605 [I] [asm_amd64.s:1581]  down<geoip.dat> 7576504-8523566

2022/03/14 00:01:32.607 [I] [asm_amd64.s:1581]  down<geoip.dat> 1894126-2841188

2022/03/14 00:01:32.607 [I] [asm_amd64.s:1581]  down<geoip.dat> 13258882-14205944

2022/03/14 00:01:32.607 [I] [asm_amd64.s:1581]  down<geoip.dat> 2841189-3788251

2022/03/14 00:01:46.966 [I] [pre.go:243]  download[geoip.dat]: SUCCESS

2022/03/14 00:01:48.477 [I] [asm_amd64.s:1581]  down<dlc.dat> 1010460-1077825

2022/03/14 00:01:48.477 [I] [asm_amd64.s:1581]  down<dlc.dat> 0-67363

2022/03/14 00:01:48.477 [I] [asm_amd64.s:1581]  down<dlc.dat> 538912-606275

2022/03/14 00:01:48.477 [I] [asm_amd64.s:1581]  down<dlc.dat> 202092-269455

2022/03/14 00:01:48.477 [I] [asm_amd64.s:1581]  down<dlc.dat> 606276-673639

2022/03/14 00:01:48.477 [I] [asm_amd64.s:1581]  down<dlc.dat> 336820-404183

2022/03/14 00:01:48.477 [I] [asm_amd64.s:1581]  down<dlc.dat> 404184-471547

2022/03/14 00:01:48.477 [I] [asm_amd64.s:1581]  down<dlc.dat> 943096-1010459

2022/03/14 00:01:48.477 [I] [asm_amd64.s:1581]  down<dlc.dat> 269456-336819

2022/03/14 00:01:48.477 [I] [asm_amd64.s:1581]  down<dlc.dat> 134728-202091

2022/03/14 00:01:48.477 [I] [asm_amd64.s:1581]  down<dlc.dat> 673640-741003

2022/03/14 00:01:48.477 [I] [asm_amd64.s:1581]  down<dlc.dat> 875732-943095

2022/03/14 00:01:48.478 [I] [asm_amd64.s:1581]  down<dlc.dat> 741004-808367

2022/03/14 00:01:48.477 [I] [asm_amd64.s:1581]  down<dlc.dat> 67364-134727

2022/03/14 00:01:48.477 [I] [asm_amd64.s:1581]  down<dlc.dat> 808368-875731

2022/03/14 00:01:48.477 [I] [asm_amd64.s:1581]  down<dlc.dat> 471548-538911

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/v2rayA/v2rayA/core/v2ray/asset/dat.UpdateLocalGeoSite()
	/home/runner/work/v2rayA/v2rayA/service/core/v2ray/asset/dat/geosite.go:30 +0x3dc
main.initConfigure()
	/home/runner/work/v2rayA/v2rayA/service/pre.go:249 +0x4ce
main.main()
	/home/runner/work/v2rayA/v2rayA/service/main.go:25 +0x6a

```
