### ISSUE TITLE
go panic with go 1.18

### ISSUE THREAD

**Issue by linyana** [v2rayA/v2rayA#460]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
heads/master & 1.5.6.2
2. 你通过什么方式安装v2rayA
build-in-pwsh.ps1 编译然后手动执行
3. 你所使用的操作系统
Win11

### 描述问题：

用go1.18编译,执行直接报错

### v2rayA运行日志（Optional）：

```shell
.\v2raya.exe --lite
调试:    1+  >>>> .\v2raya.exe --lite
unexpected fault address 0xffffffffffffffff
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xffffffffffffffff pc=0xae153f]

goroutine 1 [running]:
runtime.throw({0x13f49f4?, 0x231e8a79958?})
        D:/Go/src/runtime/panic.go:992 +0x76 fp=0xc00056f960 sp=0xc00056f930 pc=0xab6c76
runtime.sigpanic()
        D:/Go/src/runtime/signal_windows.go:261 +0x125 fp=0xc00056f9a8 sp=0xc00056f960 pc=0xac9c65
aeshashbody()
        D:/Go/src/runtime/asm_amd64.s:1343 +0x39f fp=0xc00056f9b0 sp=0xc00056f9a8 pc=0xae153f
runtime.mapiternext(0xc0003ed240)
        D:/Go/src/runtime/map.go:934 +0x2cb fp=0xc00056fa20 sp=0xc00056f9b0 pc=0xa8ffeb
runtime.mapiterinit(0xc0004013b0?, 0xc0003c30b0?, 0x100c0003c2ee0?)
        D:/Go/src/runtime/map.go:861 +0x228 fp=0xc00056fa40 sp=0xc00056fa20 pc=0xa8fcc8
reflect.mapiterinit(0x0?, 0xc00056fae8?, 0xa8d805?)
        D:/Go/src/runtime/map.go:1373 +0x19 fp=0xc00056fa68 sp=0xc00056fa40 pc=0xadd3d9
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
        C:/Users/Leo/go/pkg/mod/github.com/modern-go/reflect2@v0.0.0-20180701023420-4b7aa43c6742/unsafe_map.go:112
github.com/json-iterator/go.(*mapEncoder).Encode(0xc000401380, 0xc00008e480, 0xc0000869c0)
        C:/Users/Leo/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_map.go:257 +0x21c fp=0xc00056fb20 sp=0xc00056fa68 pc=0x103a73c
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc0003c3080, 0xc000401170, 0xc0003ed240?)
        C:/Users/Leo/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:219 +0x82 fp=0xc00056fb58 sp=0xc00056fb20 pc=0x1033202
github.com/json-iterator/go.(*Stream).WriteVal(0xc0000869c0, {0x12f87c0, 0xc000401170})
        C:/Users/Leo/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x158 fp=0xc00056fbc8 sp=0xc00056fb58 pc=0x1032518
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc000620000, {0x12f87c0, 0xc000401170})
        C:/Users/Leo/go/pkg/mod/github.com/json-iterator/go@v1.1.11/config.go:299 +0xc9 fp=0xc00056fc60 sp=0xc00056fbc8 pc=0x1029629
github.com/json-iterator/go.Marshal(...)
        C:/Users/Leo/go/pkg/mod/github.com/json-iterator/go@v1.1.11/adapter.go:34
github.com/v2rayA/v2rayA/pkg/util/log.SetLogFile({0x13f8fd3?, 0x13eff5a?}, {0x0?, 0x800001e800000002?}, 0x1b?, 0x0, 0x0)
        C:/Users/Leo/Desktop/v2rayA/service/pkg/util/log/log.go:44 +0x145 fp=0xc00056fce0 sp=0xc00056fc60 pc=0x1061b25
github.com/v2rayA/v2rayA/pkg/util/log.InitLog({0x13f8fd3?, 0x1b?}, {0x0?, 0xc000068130?}, {0x13008f1, 0x4}, 0xffffffffffffffff?, 0x9?, 0x8d?)
        C:/Users/Leo/Desktop/v2rayA/service/pkg/util/log/log.go:35 +0x3a fp=0xc00056fd20 sp=0xc00056fce0 pc=0x10618da
github.com/v2rayA/v2rayA/conf.initFunc()
        C:/Users/Leo/Desktop/v2rayA/service/conf/environmentConfig.go:86 +0x510 fp=0xc00056fe18 sp=0xc00056fd20 pc=0x10622d0
sync.(*Once).doSlow(0xa8cfbe?, 0x231e8a7b828?)
        D:/Go/src/sync/once.go:68 +0xc2 fp=0xc00056fe78 sp=0xc00056fe18 pc=0xaefc02
sync.(*Once).Do(...)
        D:/Go/src/sync/once.go:59
github.com/v2rayA/v2rayA/conf.GetEnvironmentConfig(...)
        C:/Users/Leo/Desktop/v2rayA/service/conf/environmentConfig.go:92
main.checkEnvironment()
        C:/Users/Leo/Desktop/v2rayA/service/pre.go:33 +0x45 fp=0xc00056ff38 sp=0xc00056fe78 pc=0x124cb45
main.main()
        C:/Users/Leo/Desktop/v2rayA/service/main.go:21 +0x5f fp=0xc00056ff80 sp=0xc00056ff38 pc=0x124ca5f
runtime.main()
        D:/Go/src/runtime/proc.go:250 +0x1fe fp=0xc00056ffe0 sp=0xc00056ff80 pc=0xab927e
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00056ffe8 sp=0xc00056ffe0 pc=0xae42a1

goroutine 10 [sleep]:
time.Sleep(0x3b9aca00)
        D:/Go/src/runtime/time.go:194 +0x133
github.com/mzz2017/go-engine/src/common.updateNowInSecond()
        C:/Users/Leo/go/pkg/mod/github.com/mzz2017/go-engine@v0.0.0-20200509094339-b56921189229/src/common/time.go:23 +0x46
created by github.com/mzz2017/go-engine/src/common.init.1
        C:/Users/Leo/go/pkg/mod/github.com/mzz2017/go-engine@v0.0.0-20200509094339-b56921189229/src/common/time.go:11 +0x51

```

**Comment by MarksonHon** [comment]
Fixed in latest commit
