### ISSUE TITLE
Upgrade to Ubuntu 22.04 LTS Problem

### ISSUE THREAD

**Issue by hsghost** [v2rayA/v2rayA#523]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
1.5.7

2. What approach of installation do you install V2rayA?
apt install

3. What is your operating system?
Ubuntu 22.04 LTS (upgraded from 21.10)

### Description
There's only one option under Transparent Proxy setting - "system proxy". Yet, when I tried to start the v2ray service v2rayA gave the following error message: 

`failed to start v2ray-core: not support "system proxy" mode of transparent proxy: does not support to configure system proxy on your OS`

Am I missing something during the system upgrade?

I've already tried to uninstall and re-install v2rayA.

### Logs：

 ```
2022/05/09 16:50:25.236 [I] [geosite.go:17] Downloading https://hubmirror.v2raya.org/v2fly/domain-list-community/releases/latest/download/dlc.dat to /home/-------/.local/share/v2ray/geosite.dat.new
2022/05/09 16:50:27.526 [I] [pre.go:249] download[geosite.dat]: SUCCESS
2022/05/09 16:50:27.564 [A] [main.go:27] V2Ray binary is /usr/bin/v2ray
2022/05/09 16:50:27.564 [A] [main.go:27] V2Ray asset directory is /run/user/1000/v2raya
2022/05/09 16:50:27.565 [A] [main.go:27] v2rayA working directory is /home/-------
2022/05/09 16:50:27.565 [A] [main.go:27] v2rayA configuration directory is /home/-------/.config/v2raya
2022/05/09 16:50:27.565 [A] [main.go:27] Golang: go1.18
2022/05/09 16:50:27.565 [A] [main.go:27] OS: linux
2022/05/09 16:50:27.565 [A] [main.go:27] Arch: amd64
2022/05/09 16:50:27.565 [A] [main.go:27] Lite: true
2022/05/09 16:50:27.565 [A] [main.go:27] Version: 1.5.7
2022/05/09 16:50:27.565 [A] [main.go:27] Starting...
2022/05/09 16:50:27.565 [I] [main.go:28] the core was not running the last time v2rayA exited
2022/05/09 16:50:27.606 [A] [index.go:117] v2rayA is listening at http://127.0.0.1:2017
2022/05/09 16:50:27.607 [A] [index.go:117] v2rayA is listening at http://192.168.1.109:2017
2022/05/09 16:50:27.607 [A] [index.go:117] v2rayA is listening at http://[::1]:2017
2022/05/09 16:50:27.607 [A] [index.go:117] v2rayA is listening at http://[fe80::22be:6344:af07:c978]:2017
2022/05/09 17:04:49.359 [I] [io.go:428] V2Ray 4.34.0 (user) 20220118-150717 (go1.17.3 linux/amd64)
2022/05/09 17:04:49.364 [I] [io.go:428] A unified platform for anti-censorship.
2022/05/09 17:04:49.364 [I] [io.go:428] [Info] v2ray.com/core/main/jsonem: Reading config: /home/-------/.config/v2raya/config.json
2022/05/09 17:04:49.381 [I] [io.go:428] [Warning] v2ray.com/core: V2Ray 4.34.0 started
2022/05/09 17:04:49.645 [I] [io.go:428] panic: crypto/hmac: hash generation function does not produce unique values
2022/05/09 17:04:49.645 [I] [io.go:428]
2022/05/09 17:04:49.645 [I] [io.go:428] goroutine 42 [running]:
2022/05/09 17:04:49.647 [I] [io.go:428] crypto/hmac.New
2022/05/09 17:04:49.648 [I] [io.go:428] (0xc0002b4bc0, {0xc00031a0a8, 0x18, 0x18})
2022/05/09 17:04:49.648 [I] [io.go:428] crypto/hmac/hmac.go:143 +0x292
2022/05/09 17:04:49.648 [I] [io.go:428] v2ray.com/core/proxy/vmess/aead.KDF({0xc00016c110, 0x10, 0x10}, {0xc0002b4e18, 0x1, 0x0})
2022/05/09 17:04:49.648 [I] [io.go:428] v2ray.com/core/proxy/vmess/aead/kdf.go:13 +0x127
2022/05/09 17:04:49.648 [I] [io.go:428] v2ray.com/core/proxy/vmess/aead.KDF16(...)
2022/05/09 17:04:49.648 [I] [io.go:428] v2ray.com/core/proxy/vmess/aead/kdf.go:22
2022/05/09 17:04:49.648 [I] [io.go:428] v2ray.com/core/proxy/vmess/encoding.(*ClientSession).DecodeResponseHeader(0xc00016c0e0, {0xd51be0, 0xc000224fc0})
2022/05/09 17:04:49.648 [I] [io.go:428] v2ray.com/core/proxy/vmess/encoding/client.go:195 +0xcb
2022/05/09 17:04:49.648 [I] [io.go:428] v2ray.com/core/proxy/vmess/outbound.(*Handler).Process.func3()
2022/05/09 17:04:49.648 [I] [io.go:428] v2ray.com/core/proxy/vmess/outbound/outbound.go:161 +0x156
2022/05/09 17:04:49.648 [I] [io.go:428] v2ray.com/core/common/task.OnSuccess.func1()
2022/05/09 17:04:49.648 [I] [io.go:428] v2ray.com/core/common/task/task.go:12 +0x25
2022/05/09 17:04:49.648 [I] [io.go:428] v2ray.com/core/common/task.Run.func1(0x0)
2022/05/09 17:04:49.648 [I] [io.go:428] v2ray.com/core/common/task/task.go:28 +0x2e
2022/05/09 17:04:49.649 [I] [io.go:428] created by v2ray.com/core/common/task.Run
2022/05/09 17:04:49.649 [I] [io.go:428] v2ray.com/core/common/task/task.go:27 +0xe5
2022/05/09 17:04:49.652 [W] [asm_amd64.s:1571] v2ray-core: exit status 2
2022/05/09 17:05:13.894 [I] [io.go:428] V2Ray 4.34.0 (user) 20220118-150717 (go1.17.3 linux/amd64)
2022/05/09 17:05:13.894 [I] [io.go:428] A unified platform for anti-censorship.
2022/05/09 17:05:13.895 [I] [io.go:428] [Info] v2ray.com/core/main/jsonem: Reading config: /home/-------/.config/v2raya/config.json
2022/05/09 17:05:13.919 [I] [io.go:428] [Warning] v2ray.com/core: V2Ray 4.34.0 started
2022/05/09 17:06:18.167 [I] [io.go:428] V2Ray 4.34.0 (user) 20220118-150717 (go1.17.3 linux/amd64)
2022/05/09 17:06:18.167 [I] [io.go:428] A unified platform for anti-censorship.
2022/05/09 17:06:18.168 [I] [io.go:428] [Info] v2ray.com/core/main/jsonem: Reading config: /home/-------/.config/v2raya/config.json
2022/05/09 17:06:20.580 [I] [io.go:428] 127.0.0.1:60004 accepted tcp:127.0.0.1:0 [api-out]
2022/05/09 17:10:22.105 [I] [io.go:428] V2Ray 4.34.0 (user) 20220118-150717 (go1.17.3 linux/amd64)
2022/05/09 17:10:22.115 [I] [io.go:428] A unified platform for anti-censorship.
2022/05/09 17:10:22.115 [I] [io.go:428] [Info] v2ray.com/core/main/jsonem: Reading config: /home/-------/.config/v2raya/config.json
2022/05/09 17:10:24.720 [I] [io.go:428] 127.0.0.1:52544 accepted tcp:127.0.0.1:0 [api-out]
2022/05/10 14:45:43.931 [A] [main.go:25] network is connected
2022/05/10 14:45:44.228 [A] [main.go:27] V2Ray binary is /usr/bin/v2ray
2022/05/10 14:45:44.230 [A] [main.go:27] V2Ray asset directory is /run/user/1000/v2raya
2022/05/10 14:45:44.230 [A] [main.go:27] v2rayA working directory is /home/-------
2022/05/10 14:45:44.230 [A] [main.go:27] v2rayA configuration directory is /home/-------/.config/v2raya
2022/05/10 14:45:44.230 [A] [main.go:27] Golang: go1.18
2022/05/10 14:45:44.230 [A] [main.go:27] OS: linux
2022/05/10 14:45:44.230 [A] [main.go:27] Arch: amd64
2022/05/10 14:45:44.230 [A] [main.go:27] Lite: true
2022/05/10 14:45:44.230 [A] [main.go:27] Version: 1.5.7
2022/05/10 14:45:44.230 [A] [main.go:27] Starting...
2022/05/10 14:45:44.601 [I] [io.go:428] V2Ray 4.34.0 (user) 20220118-150717 (go1.17.3 linux/amd64)
2022/05/10 14:45:44.601 [I] [io.go:428] A unified platform for anti-censorship.
2022/05/10 14:45:44.603 [I] [io.go:428] [Info] v2ray.com/core/main/jsonem: Reading config: /home/-------/.config/v2raya/config.json
2022/05/10 14:45:47.027 [I] [io.go:428] 127.0.0.1:39260 accepted tcp:127.0.0.1:0 [api-out]
2022/05/10 14:45:47.068 [A] [index.go:117] v2rayA is listening at http://127.0.0.1:2017
2022/05/10 14:45:47.068 [A] [index.go:117] v2rayA is listening at http://192.168.1.109:2017
2022/05/10 14:45:47.068 [A] [index.go:117] v2rayA is listening at http://[::1]:2017
2022/05/10 14:45:47.068 [A] [index.go:117] v2rayA is listening at http://[fe80::22be:6344:af07:c978]:2017
2022/05/10 14:47:59.692 [I] [io.go:428] V2Ray 4.34.0 (user) 20220118-150717 (go1.17.3 linux/amd64)
2022/05/10 14:47:59.697 [I] [io.go:428] A unified platform for anti-censorship.
2022/05/10 14:47:59.697 [I] [io.go:428] [Info] v2ray.com/core/main/jsonem: Reading config: /home/-------/.config/v2raya/config.json
2022/05/10 14:48:04.516 [I] [io.go:428] 127.0.0.1:47868 accepted tcp:127.0.0.1:0 [api-out]
2022/05/10 14:48:04.629 [W] [transparent.go:56] WriteTransparentProxyRules: not support "system proxy" mode of transparent proxy: does not support to configure system proxy on your OS
2022/05/10 14:48:04.841 [E] [setting.go:51] invalid config: not support "system proxy" mode of transparent proxy: does not support to configure system proxy on your OS
2022/05/10 14:48:33.428 [I] [io.go:428] V2Ray 4.34.0 (user) 20220118-150717 (go1.17.3 linux/amd64)
 ```
Note: the successful connection in log was before I enabled transparent proxy. Yet I need it to be transparent, of course.

**Comment by mzz2017** [comment]
use v2raya.service instead of v2raya-lite.service
