### ISSUE TITLE
The config generated by v2raya cannot be loaded by v2ray-core

### ISSUE THREAD

**Issue by byte1234** [v2rayA/v2rayA#574]
log:
```txt
2022/06/25 18:34:07.361 [I] [io.go:428] V2Ray 4.34.0 (user) 20210718-110034 (go1.15.9 linux/amd64)
2022/06/25 18:34:07.361 [I] [io.go:428] A unified platform for anti-censorship.
2022/06/25 18:34:07.361 [I] [io.go:428] [Info] v2ray.com/core/main/jsonem: Reading config: /home/moe/.config/v2raya/config.json
2022/06/25 18:34:07.364 [I] [io.go:428] panic: v2ray.com/core/infra/conf/serial: failed to read config file at line 1 char 1 > v2ray.com/core/infra/conf: invalid address: ["1-courier.push.apple.com"] > json: cannot unmarshal array into Go value of type string
2022/06/25 18:34:07.364 [I] [io.go:428]
2022/06/25 18:34:07.364 [I] [io.go:428] goroutine 1 [running]:
2022/06/25 18:34:07.364 [I] [io.go:428] v2ray.com/core/common.Must(...)
2022/06/25 18:34:07.364 [I] [io.go:428] v2ray.com/core/common/common.go:26
2022/06/25 18:34:07.364 [I] [io.go:428] v2ray.com/core/main/jsonem.init.0.func1(0xc9ae00, 0xc0001ce640, 0x7ffd0d2cfa38, 0x4, 0xc0000b58f0)
2022/06/25 18:34:07.364 [I] [io.go:428] v2ray.com/core/main/jsonem/jsonem.go:27
2022/06/25 18:34:07.364 [I] [io.go:428] +0x473
2022/06/25 18:34:07.364 [I] [io.go:428] v2ray.com/core.LoadConfig(0xddeaa8, 0x4, 0x7ffd0d2cfa18, 0x24, 0xc9ae00, 0xc0001ce640, 0xc0001ade98, 0xc00106, 0xeea2c0)
2022/06/25 18:34:07.364 [I] [io.go:428] v2ray.com/core/config.go:66 +0x262
2022/06/25 18:34:07.364 [I] [io.go:428] main.startV2Ray(0xc00009c1e0, 0xc00000e070, 0x1, 0x1)
2022/06/25 18:34:07.364 [I] [io.go:428] v2ray.com/core/main/main.go:110 +0x12e
2022/06/25 18:34:07.364 [I] [io.go:428] main.main()
2022/06/25 18:34:07.364 [I] [io.go:428] v2ray.com/core/main/main.go:139 +0xb1
2022/06/25 18:34:07.365 [W] [asm_amd64.s:1571] v2ray-core: exit status 2
2022/06/25 18:34:07.557 [W] [context.go:165] PostConnection: failed to connect: unexpected exiting: check the log for more information
2022/06/25 18:34:07.557 [E] [connection.go:36] failed to connect: failed to connect: unexpected exiting: check the log for more information
2022/06/25 18:55:38.857 [I] [io.go:428] V2Ray 4.34.0 (user) 20210718-110034 (go1.15.9 linux/amd64)
2022/06/25 18:55:38.857 [I] [io.go:428] A unified platform for anti-censorship.
2022/06/25 18:55:38.857 [I] [io.go:428] [Info] v2ray.com/core/main/jsonem: Reading config: /home/moe/.config/v2raya/config.json
2022/06/25 18:55:38.861 [I] [io.go:428] panic: v2ray.com/core/infra/conf/serial: failed to read config file at line 1 char 1 > v2ray.com/core/infra/conf: invalid address: ["1-courier.push.apple.com"] > json: cannot unmarshal array into Go value of type string
2022/06/25 18:55:38.861 [I] [io.go:428]
2022/06/25 18:55:38.861 [I] [io.go:428] goroutine 1 [running]:
2022/06/25 18:55:38.861 [I] [io.go:428] v2ray.com/core/common.Must(...)
2022/06/25 18:55:38.861 [I] [io.go:428] v2ray.com/core/common/common.go:26
2022/06/25 18:55:38.861 [I] [io.go:428] v2ray.com/core/main/jsonem.init.0.func1(0xc9ae00, 0xc0001d0640, 0x7ffd5bb50a38, 0x4, 0xc0000b5410)
2022/06/25 18:55:38.861 [I] [io.go:428] v2ray.com/core/main/jsonem/jsonem.go:27
2022/06/25 18:55:38.861 [I] [io.go:428] +0x473
2022/06/25 18:55:38.861 [I] [io.go:428] v2ray.com/core.LoadConfig(0xddeaa8, 0x4, 0x7ffd5bb50a18, 0x24, 0xc9ae00, 0xc0001d0640, 0xc0001abe98, 0xc00106, 0xeea2c0)
2022/06/25 18:55:38.861 [I] [io.go:428] v2ray.com/core/config.go:66 +0x262
2022/06/25 18:55:38.861 [I] [io.go:428] main.startV2Ray(0xc00009c1e0, 0xc00000e070, 0x1, 0x1)
2022/06/25 18:55:38.861 [I] [io.go:428] v2ray.com/core/main/main.go:110 +0x12e
2022/06/25 18:55:38.861 [I] [io.go:428] main.main()
2022/06/25 18:55:38.861 [I] [io.go:428] v2ray.com/core/main/main.go:139 +0xb1
2022/06/25 18:55:38.862 [W] [asm_amd64.s:1571] v2ray-core: exit status 2
2022/06/25 18:55:39.053 [W] [context.go:165] PostConnection: failed to connect: unexpected exiting: check the log for more information
2022/06/25 18:55:39.053 [E] [connection.go:36] failed to connect: failed to connect: unexpected exiting: check the log for more information
```

**Comment by mzz2017** [comment]
Your version of v2ray-core is too low. Try to upgrade it and try again.

**Comment by byte1234** [comment]
really thanks, but I'm using the debian stable, its official v2ray-core is 4.34, should v2raya pin a warning issue for debian users?
(I'll upgrade to the latest v2ray-core)

**Comment by mzz2017** [comment]
@byte1234 Yes, v2rayA used to offer old version compatibility. There may be some negligence but it seems just acceptable.

**Comment by MarchAwake** [comment]
you can delete word `run `  in  `ExecStart=/usr/bin/v2ray run -config /etc/v2ray/config.json` ,and execute command `systemctl daemon-reload`.
