### ISSUE TITLE
添加server后连接报错Failed to connect

### ISSUE THREAD

**Issue by ghost** [v2rayA/v2rayA#582]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.8.1
2. 你通过什么方式安装v2rayA
pacman -U installer_archlinux_x86_64_1.5.8.1.pkg.tar.zstd
3. 你所使用的操作系统
`5.15.49-1-MANJARO #1 SMP PREEMPT Wed Jun 22 14:15:49 UTC 2022 x86_64 GNU/Linux`
XFCE桌面

### 描述问题：
添加server后连接报错Failed to connect

本机v2ray(4.31.0)为手动安装，systemctl status显示v2ray和v2raya服务都在运行，进入web面板添加server后点击连接，报错failed to connect:failed to connect:unexpected exiting:check the log for more information,更换server，重启服务后依旧报错

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志

2022/06/30 14:50:50.073 [I] [io.go:428] V2Ray 4.31.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
2022/06/30 14:50:50.073 [I] [io.go:428] A unified platform for anti-censorship.
2022/06/30 14:50:50.094 [I] [io.go:428] main: failed to read config files: [/etc/v2raya/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl:
2022/06/30 14:50:50.094 [I] [io.go:428] v2ctl> Read config: /etc/v2raya/config.json
2022/06/30 14:50:50.094 [I] [io.go:428] v2ctl> v2ray.com/core/infra/conf/serial: failed to read config file at line 1 char 1 > v2ray.com/core/infra/conf: invalid address: ["1-courier.push.apple.com"] > json: cannot unmarshal array into Go value of type string > exit status 1
2022/06/30 14:50:50.096 [W] [asm_amd64.s:1571] v2ray-core: exit status 23
2022/06/30 14:50:50.254 [W] [context.go:165] PostConnection: failed to connect: unexpected exiting: check the log for more information
2022/06/30 14:50:50.254 [E] [connection.go:36] failed to connect: failed to connect: unexpected exiting: check the log for more information


```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![web](https://user-images.githubusercontent.com/91418079/176613643-1ba8a894-a3b1-41ab-a881-99390587fb91.png)

**Comment by mzz2017** [comment]
@MrKusta 升级你的 v2ray-core

**Comment by MrKusta** [comment]
已升级至最新，打开服务选择server后，点击启动，再次报错：
**failed to start v2ray-core: unexpected exiting: check the log for more information**
**log：**
2022/06/30 20:09:19.336 [I] [io.go:428] V2Ray 4.45.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.3 linux/amd64)
2022/06/30 20:09:19.336 [I] [io.go:428] A unified platform for anti-censorship.
2022/06/30 20:09:19.337 [I] [io.go:428] [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2022/06/30 20:09:20.439 [I] [io.go:428] panic: runtime error: index out of range [133] with length 127
2022/06/30 20:09:20.439 [I] [io.go:428]
2022/06/30 20:09:20.439 [I] [io.go:428] goroutine 1 [running]:
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/common/strmatcher.(*ACAutomaton).Add(0xc0042705f0, {0xc000b52260, 0xc003c06808?}, 0x1)
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/common/strmatcher/ac_automaton_matcher.go:138 +0x694
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/common/strmatcher.(*MphMatcherGroup).AddPattern(0xc0037b8ab0, {0xc000b52260?, 0x1b?}, 0x1)
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/common/strmatcher/mph_matcher.go:72 +0x28e
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/app/router.NewMphMatcherGroup({0xc0003b4720, 0x1, 0x556be4c87500?})
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/app/router/condition.go:79 +0x13b
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/app/router.(*RoutingRule).BuildCondition(0xc000035080)
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/app/router/config.go:36 +0xfd
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/app/router.(*Router).Init(0xc003a48140, {0x556be4ddebf0, 0xc0037b6f90}, 0xc000ddb380, {0x7f79d904c2f0?, 0xc0037b2e80?}, {0x7f79d90478b8?, 0xc0037ad090})
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/app/router/router.go:51 +0x445
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/app/router.init.1.func1.1({0x7f79d904c2f0?, 0xc0037b2e80?}, {0x7f79d90478b8?, 0xc0037ad090?})
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/app/router/router.go:147 +0x6f
2022/06/30 20:09:20.439 [I] [io.go:428] reflect.Value.call({0x556be4c81e60?, 0xc0037b6fc0?, 0x30?
2022/06/30 20:09:20.439 [I] [io.go:428] }, {0x556be4a79692, 0x4}, {0xc0037b7680, 0x2, 0x18?})
2022/06/30 20:09:20.439 [I] [io.go:428] reflect/value.go:556 +0x845
2022/06/30 20:09:20.439 [I] [io.go:428] reflect.Value.Call({0x556be4c81e60?, 0xc0037b6fc0?, 0x556be4d08c00?}, {0xc0037b7680, 0x2, 0x2})
2022/06/30 20:09:20.439 [I] [io.go:428] reflect/value.go:339 +0xbf
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4.(*resolution).resolve(0xc003c07c78?, {0xc0037b2980?, 0x7?, 0x8?})
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/v2ray.go:75 +0x3d4
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4.(*Instance).AddFeature(0xc0037acff0, {0x7f79d904c2c0?, 0xc0037b2e80?})
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/v2ray.go:306 +0x31e
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4.initInstanceWithConfig(0xc000503560, 0xc0037acff0)
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/v2ray.go:202 +0x19c
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4.New(0x556be4a79ae6?)
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/v2ray.go:165 +0x77
2022/06/30 20:09:20.439 [I] [io.go:428] main.startV2Ray()
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/main/main.go:114 +0x265
2022/06/30 20:09:20.439 [I] [io.go:428] main.main()
2022/06/30 20:09:20.439 [I] [io.go:428] github.com/v2fly/v2ray-core/v4/main/main.go:138 +0x9f
2022/06/30 20:09:20.446 [W] [asm_amd64.s:1571] v2ray-core: exit status 2
2022/06/30 20:09:20.483 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information

**Comment by MrKusta** [comment]
@mzz2017 
![截图_2022-06-30_20-51-44](https://user-images.githubusercontent.com/91418079/176681528-2b4c45fa-97ae-461c-9f80-3dbd6283a23c.png)

**Comment by MrKusta** [comment]
@mzz2017

**Comment by MrKusta** [comment]
![截图_2022-06-30_20-51-44](https://user-images.githubusercontent.com/91418079/176682160-f319b2f1-2cb8-4120-8245-0a0c99de83c1.png)
@mzz2017

**Comment by mzz2017** [comment]
换4.44版本
