### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by gqcdm** [v2rayA/v2rayA#607]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.9.1698-1
2. 你通过什么方式安装v2rayA
pacman
3. 你所使用的操作系统
ArchLinux

### 描述问题

![image](https://user-images.githubusercontent.com/78142321/182773958-4e01033d-e7b6-4a34-a5c7-fc14670cfc15.png)

### 复现问题的步骤

使用pacman更新为最新版本

### v2rayA/v2ray运行日志：
```
8月 04 13:53:18 arch systemd[1]: Failed to start v2rayA Service.
-- Boot a607327e6f0641c1a50d9e425d732737 --
8月 04 13:54:00 arch systemd[1]: Started v2rayA Service.
8月 04 13:54:00 arch v2raya[557]: panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.19 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.19 set. Notably, if go1.19 adds a moving garbage collector, this program is unsafe to use.
8月 04 13:54:00 arch v2raya[557]: goroutine 1 [running]:
8月 04 13:54:00 arch v2raya[557]: go4.org/unsafe/assume-no-moving-gc.init.0()
8月 04 13:54:00 arch v2raya[557]:         go4.org/unsafe/assume-no-moving-gc@v0.0.0-20211027215541-db492cf91b37/untested.go:25 +0x1f4
8月 04 13:54:00 arch systemd[1]: v2raya.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
8月 04 13:54:00 arch systemd[1]: v2raya.service: Failed with result 'exit-code'.
8月 04 13:54:00 arch systemd[1]: v2raya.service: Scheduled restart job, restart counter is at 1.
8月 04 13:54:00 arch systemd[1]: Stopped v2rayA Service.
8月 04 13:54:00 arch systemd[1]: Started v2rayA Service.
8月 04 13:54:00 arch v2raya[632]: panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.19 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.19 set. Notably, if go1.19 adds a moving garbage collector, this program is unsafe to use.
8月 04 13:54:00 arch v2raya[632]: goroutine 1 [running]:
8月 04 13:54:00 arch v2raya[632]: go4.org/unsafe/assume-no-moving-gc.init.0()
8月 04 13:54:00 arch v2raya[632]:         go4.org/unsafe/assume-no-moving-gc@v0.0.0-20211027215541-db492cf91b37/untested.go:25 +0x1f4
8月 04 13:54:00 arch systemd[1]: v2raya.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
8月 04 13:54:00 arch systemd[1]: v2raya.service: Failed with result 'exit-code'.
8月 04 13:54:01 arch systemd[1]: v2raya.service: Scheduled restart job, restart counter is at 2.
8月 04 13:54:01 arch systemd[1]: Stopped v2rayA Service.
8月 04 13:54:01 arch systemd[1]: Started v2rayA Service.
8月 04 13:54:01 arch v2raya[653]: panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.19 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.19 set. Notably, if go1.19 adds a moving garbage collector, this program is unsafe to use.
8月 04 13:54:01 arch v2raya[653]: goroutine 1 [running]:
8月 04 13:54:01 arch v2raya[653]: go4.org/unsafe/assume-no-moving-gc.init.0()
8月 04 13:54:01 arch v2raya[653]:         go4.org/unsafe/assume-no-moving-gc@v0.0.0-20211027215541-db492cf91b37/untested.go:25 +0x1f4
8月 04 13:54:01 arch systemd[1]: v2raya.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
8月 04 13:54:01 arch systemd[1]: v2raya.service: Failed with result 'exit-code'.
8月 04 13:54:01 arch systemd[1]: v2raya.service: Scheduled restart job, restart counter is at 3.
8月 04 13:54:01 arch systemd[1]: Stopped v2rayA Service.
8月 04 13:54:01 arch systemd[1]: Started v2rayA Service.
8月 04 13:54:01 arch v2raya[704]: panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.19 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.19 set. Notably, if go1.19 adds a moving garbage collector, this program is unsafe to use.
8月 04 13:54:01 arch v2raya[704]: goroutine 1 [running]:
8月 04 13:54:01 arch v2raya[704]: go4.org/unsafe/assume-no-moving-gc.init.0()
8月 04 13:54:01 arch v2raya[704]:         go4.org/unsafe/assume-no-moving-gc@v0.0.0-20211027215541-db492cf91b37/untested.go:25 +0x1f4
8月 04 13:54:01 arch systemd[1]: v2raya.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
8月 04 13:54:01 arch systemd[1]: v2raya.service: Failed with result 'exit-code'.
8月 04 13:54:01 arch systemd[1]: v2raya.service: Scheduled restart job, restart counter is at 4.
8月 04 13:54:01 arch systemd[1]: Stopped v2rayA Service.
8月 04 13:54:01 arch systemd[1]: Started v2rayA Service.
8月 04 13:54:01 arch v2raya[726]: panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.19 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.19 set. Notably, if go1.19 adds a moving garbage collector, this program is unsafe to use.
8月 04 13:54:01 arch v2raya[726]: goroutine 1 [running]:
8月 04 13:54:01 arch v2raya[726]: go4.org/unsafe/assume-no-moving-gc.init.0()
8月 04 13:54:01 arch v2raya[726]:         go4.org/unsafe/assume-no-moving-gc@v0.0.0-20211027215541-db492cf91b37/untested.go:25 +0x1f4
8月 04 13:54:01 arch systemd[1]: v2raya.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
8月 04 13:54:01 arch systemd[1]: v2raya.service: Failed with result 'exit-code'.
8月 04 13:54:01 arch systemd[1]: v2raya.service: Scheduled restart job, restart counter is at 5.
8月 04 13:54:01 arch systemd[1]: Stopped v2rayA Service.
8月 04 13:54:01 arch systemd[1]: v2raya.service: Start request repeated too quickly.
8月 04 13:54:01 arch systemd[1]: v2raya.service: Failed with result 'exit-code'.
8月 04 13:54:01 arch systemd[1]: Failed to start v2rayA Service.
```

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
上午修复了，再更新一下最新版

**Comment by gqcdm** [comment]
感谢,由于兰州大的archlinuxcn源更新慢导致
