### ISSUE TITLE
HTTP时延测试失败

### ISSUE THREAD

**Issue by BladPit** [v2rayA/v2rayA#623]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
1.5.9.1698.1
2. What approach of installation do you install V2rayA?
docker
3. What is your operating system?
unraid 6.8.2

### Description

先是在1.5.6版本进行所有节点（111个）的http时延测试时，等待了大概30秒左右，就会终止测试，并且弹出错误提示【unexpected exiting: check the log for more information】，相关log如下，多次测试均是一样的情况，后面升级了docker到最新版本1.5.9.1698.1，也是一样的报错。
但如果是ping测试则可以正常完成，而且大约1个月以前也是可以正常完成所有节点http的时延测试的（中间有1个月左右没有用过v2rayA）

但奇怪的是，我如果不勾选所有节点，只是勾选很少数量的几个节点，http时延测试是可以完成并显示结果的，不过log里面似乎也会报错：
`2022/08/13 01:23:30.043 [1;34m[I][0m [io.go:429] V2Ray 4.45.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.3 linux/amd64)
2022/08/13 01:23:30.043 [1;34m[I][0m [io.go:429] A unified platform for anti-censorship.
2022/08/13 01:23:30.044 [1;34m[I][0m [io.go:429] [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2022/08/13 01:23:30.048 [1;34m[I][0m [io.go:429] [Warning] V2Ray 4.45.2 started`
### Logs：
`2022/08/13 01:09:53.115 [1;34m[I][0m [io.go:429] V2Ray 4.45.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.3 linux/amd64)
2022/08/13 01:09:53.115 [1;34m[I][0m [io.go:429] A unified platform for anti-censorship.
2022/08/13 01:09:53.115 [1;34m[I][0m [io.go:429] [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] panic: runtime error: invalid memory address or nil pointer dereference

2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc00d4e
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] ]
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429]
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] goroutine 1 [running]:
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] github.com/v2fly/v2ray-core/v4/infra/conf.getHostMapping(0x0)
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] github.com/v2fly/v2ray-core/v4/infra/conf/dns.go:167 +0x2e
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] github.com/v2fly/v2ray-core/v4/infra/conf.(*DNSConfig).Build(0xc00009c870)
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] github.com/v2fly/v2ray-core/v4/infra/conf/dns.go:341 +0x1405
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] github.com/v2fly/v2ray-core/v4/infra/conf.(*Config).Build(0xc0001c81c0)
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] github.com/v2fly/v2ray-core/v4/infra/conf/v2ray.go:545 +0x5b1
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] github.com/v2fly/v2ray-core/v4/main/jsonem.init.0.func1({0xcb3600?, 0xc0000bdf68?
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] })
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] github.com/v2fly/v2ray-core/v4/main/jsonem/jsonem.go:36 +0x313
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] github.com/v2fly/v2ray-core/v4.LoadConfig({0xe0b26e, 0x4}, {0x7ffcddccfef3?, 0x0?}, {0xcb3600, 0xc0000bdf68})
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] github.com/v2fly/v2ray-core/v4/config.go:
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] 68 +0x1f7
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] main.startV2Ray()
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] github.com/v2fly/v2ray-core/v4/main/main.go:109 +0xed
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] main.main()
2022/08/13 01:09:53.131 [1;34m[I][0m [io.go:429] github.com/v2fly/v2ray-core/v4/main/main.go:138 +0x9f
2022/08/13 01:09:53.901 [1;33m[W][0m [asm_amd64.s:1594] v2ray-core: exit status 2
2022/08/13 01:09:53.901 [1;31m[E][0m [latency.go:66] unexpected exiting: check the log for more information`

![image](https://user-images.githubusercontent.com/90924194/184410515-59f03453-0312-49a5-b6ce-451085f0f7f9.png)

**Comment by mzz2017** [comment]
@BladPit 请麻烦在会报错的http测试中将 /etc/v2raya/config.json 的结果贴出来，注意隐藏节点信息

**Comment by BladPit** [comment]
`{
	"log": {
		"access": "",
		"error": "none",
		"loglevel": "info"
	},
	"inbounds": [
		{
			"port": 20170,
			"protocol": "socks",
			"listen": "0.0.0.0",
			"sniffing": {
				"enabled": false,
				"destOverride": [
					"http",
					"tls"
				],
				"metadataOnly": false
			},
			"settings": {
				"auth": "noauth",
				"udp": true
			},
			"streamSettings": null,
			"tag": "socks"
		},
		{
			"port": 20171,
			"protocol": "http",
			"listen": "0.0.0.0",
			"sniffing": {
				"enabled": false,
				"destOverride": [
					"http",
					"tls"
				],
				"metadataOnly": false
			},
			"streamSettings": null,
			"tag": "http"
		},
		{
			"port": 20172,
			"protocol": "http",
			"listen": "0.0.0.0",
			"sniffing": {
				"enabled": false,
				"destOverride": [
					"http",
					"tls"
				],
				"metadataOnly": false
			},
			"streamSettings": null,
			"tag": "rule-http"
		},
		{
			"port": 32345,
			"protocol": "dokodemo-door",
			"listen": "0.0.0.0",
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				],
				"metadataOnly": false
			},
			"settings": {
				"network": "tcp,udp",
				"followRedirect": true
			},
			"streamSettings": {
				"sockopt": {
					"tproxy": "redirect"
				}
			},
			"tag": "transparent"
		},
		{
			"port": 44817,
			"protocol": "dokodemo-door",
			"listen": "127.0.0.1",
			"sniffing": {
				"enabled": false,
				"metadataOnly": false
			},
			"settings": {
				"address": "127.0.0.1"
			},
			"streamSettings": null,
			"tag": "api-in"
		}
	],
	"outbounds": [
		{
			"tag": "『香港HKT-优化』",
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "***",
						"port": 16620,
						"users": [
							{
								"id": "***",
								"security": "auto"
							}
						]
					}
				]
			},
			"streamSettings": {
				"network": "ws",
				"wsSettings": {
					"path": "",
					"headers": {
						"Host": ""
					}
				},
				"sockopt": {
					"mark": 128
				}
			}
		},
		{
			"tag": "『日本-优化2』",
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "***",,
						"port": 16617,
						"users": [
							{
								"id": "***",,
								"security": "auto"
							}
						]
					}
				]
			},
			"streamSettings": {
				"network": "ws",
				"wsSettings": {
					"path": "",
					"headers": {
						"Host": ""
					}
				},
				"sockopt": {
					"mark": 128
				}
			}
		},
		{
			"tag": "『香港Az-优化2』",
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "***",,
						"port": 16627,
						"users": [
							{
								"id": "***",,
								"security": "auto"
							}
						]
					}
				]
			},
			"streamSettings": {
				"network": "ws",
				"wsSettings": {
					"path": "",
					"headers": {
						"Host": ""
					}
				},
				"sockopt": {
					"mark": 128
				}
			}
		},
		{
			"tag": "direct",
			"protocol": "freedom",
			"settings": {
				"domainStrategy": "UseIP"
			},
			"streamSettings": {
				"sockopt": {
					"mark": 128
				}
			}
		},
		{
			"tag": "block",
			"protocol": "blackhole",
			"settings": {}
		},
		{
			"tag": "dns-out",
			"protocol": "dns",
			"settings": {
				"port": 53,
				"address": "119.29.29.29",
				"network": "udp"
			},
			"streamSettings": {
				"sockopt": {
					"mark": 128
				}
			}
		}
	],
	"routing": {
		"domainStrategy": "IPOnDemand",
		"domainMatcher": "mph",
		"rules": [
			{
				"type": "field",
				"outboundTag": "direct",
				"domain": [
					"cu.mj-cn.cyou"
				],
				"port": "16620"
			},
			{
				"type": "field",
				"outboundTag": "direct",
				"domain": [
					"cm.mjcnnode.com"
				],
				"port": "16617"
			},
			{
				"type": "field",
				"outboundTag": "direct",
				"domain": [
					"cm.mjcnnode.com"
				],
				"port": "16627"
			},
			{
				"type": "field",
				"outboundTag": "direct",
				"inboundTag": [
					"dns"
				],
				"ip": [
					"208.67.220.220"
				],
				"port": "5353"
			},
			{
				"type": "field",
				"outboundTag": "direct",
				"inboundTag": [
					"dns"
				],
				"ip": [
					"119.29.29.29"
				],
				"port": "53"
			},
			{
				"type": "field",
				"outboundTag": "direct",
				"inboundTag": [
					"dns"
				]
			},
			{
				"type": "field",
				"outboundTag": "direct",
				"inboundTag": [
					"transparent"
				],
				"ip": [
					"geoip:private",
					"127.0.0.1/8",
					"192.168.2.200/16",
					"172.18.0.1/16",
					"172.17.0.1/16",
					"192.168.2.200/32",
					"::1/128",
					"fe80::f6b5:20ff:fe3a:c9fa/64",
					"240e:399:337:bb71::2cd/128",
					"240e:399:337:bb71:a348:761f:4c22:b46a/64",
					"fe80::f6b5:20ff:fe3a:c9fa/64",
					"fe80::42:6ff:fedd:d113/64",
					"240e:399:337:bb71:8031:44ff:fed8:5250/64",
					"fe80::8031:44ff:fed8:5250/64",
					"fe80::1044:baff:fee9:b69c/64",
					"fe80::787b:d1ff:feae:a0e2/64",
					"fe80::ed:daff:fe27:d75/64",
					"fe80::1c82:f5ff:fe6c:97f5/64",
					"fe80::901f:31ff:fe4f:bdae/64"
				],
				"port": "53"
			},
			{
				"type": "field",
				"outboundTag": "direct",
				"inboundTag": [
					"rule-http",
					"rule-socks",
					"transparent"
				],
				"domain": [
					"domain:push-apple.com.akadns.net",
					"domain:push.apple.com"
				]
			},
			{
				"type": "field",
				"outboundTag": "direct",
				"inboundTag": [
					"rule-http",
					"rule-socks",
					"transparent"
				],
				"sourcePort": "51413"
			},
			{
				"type": "field",
				"balancerTag": "proxy",
				"inboundTag": [
					"rule-http",
					"rule-socks",
					"transparent"
				],
				"domain": [
					"geosite:google-scholar"
				]
			},
			{
				"type": "field",
				"outboundTag": "direct",
				"inboundTag": [
					"rule-http",
					"rule-socks",
					"transparent"
				],
				"domain": [
					"geosite:category-scholar-!cn",
					"geosite:category-scholar-cn"
				]
			},
			{
				"type": "field",
				"balancerTag": "proxy",
				"inboundTag": [
					"rule-http",
					"rule-socks",
					"transparent"
				],
				"domain": [
					"geosite:geolocation-!cn"
				]
			},
			{
				"type": "field",
				"outboundTag": "direct",
				"inboundTag": [
					"rule-http",
					"rule-socks",
					"transparent"
				]
			},
			{
				"type": "field",
				"outboundTag": "api-out",
				"inboundTag": [
					"api-in"
				]
			},
			{
				"type": "field",
				"balancerTag": "proxy",
				"network": "tcp,udp"
			}
		],
		"balancers": [
			{
				"tag": "proxy",
				"selector": [
					"『香港Az-优化2』",
					"『香港HKT-优化』",
					"『日本-优化2』"
				],
				"strategy": {
					"type": "leastPing"
				}
			}
		]
	},
	"dns": {
		"hosts": {
			"courier.push.apple.com": [
				"1-courier.push.apple.com"
			]
		},
		"servers": [
			"localhost",
			{
				"address": "tcp://208.67.220.220:5353",
				"domains": [
					"cu.mj-cn.cyou",
					"cm.mjcnnode.com"
				]
			},
			{
				"address": "tcp://119.29.29.29:53",
				"domains": [
					"cu.mj-cn.cyou",
					"cm.mjcnnode.com"
				]
			}
		],
		"tag": "dns"
	},
	"observatory": {
		"subjectSelector": [
			"『香港Az-优化2』",
			"『香港HKT-优化』",
			"『日本-优化2』"
		],
		"probeURL": "https://gstatic.com/generate_204",
		"probeInterval": "10s"
	},
	"api": {
		"tag": "api-out",
		"services": [
			"LoggerService",
			"ObservatoryService"
		]
	}
}`

**Comment by wushuangliu070** [comment]
同样的问题

**Comment by KagurazakaNyaa** [comment]
对于ipv4节点正常，但是当http测试中包含ipv6节点时出现此问题

**Comment by KagurazakaNyaa** [comment]
目前来看，仅当http测试中包含 **域名被解析为v6地址的节点** 时出错，直接 **地址为ipv6地址的节点** 可以正常被测试

**Comment by ChenSino** [comment]
> 目前来看，仅当http测试中包含 **域名被解析为v6地址的节点** 时出错，直接 **地址为ipv6地址的节点** 可以正常被测试

正解

**Comment by houzhaopeng** [comment]
> @BladPit 请麻烦在会报错的 http 测试中将 /etc/v2raya/config.json 的结果贴出来，注意隐藏节点信息

似乎在解析ipv6 dns时出错，该如何解决呢
