### ISSUE TITLE
V2ray getting slice bounds out of range

### ISSUE THREAD

**Issue by malikshi** [v2rayA/v2rayA#654]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
1.5.9.1698.1
2. What approach of installation do you install V2rayA?
https://v2raya.org/en/docs/prologue/installation/debian/#method-1-install-through-the-software-source
3. What is your operating system?
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```

 You can also paste the log that comes from web administration page

```shell
# Paste running logs here
2022/09/15 22:53:34.621  [I] [io.go:428]  panic:
2022/09/15 22:53:34.622  [I] [io.go:428]  runtime error: slice bounds out of range [:-22]
2022/09/15 22:53:34.622  [I] [io.go:428]
2022/09/15 22:53:34.622  [I] [io.go:428]
2022/09/15 22:53:34.628  [I] [io.go:428]  goroutine 331119 [running]:
2022/09/15 22:53:34.631  [I] [io.go:428]  github.com/v2fly/v2ray-core/v4/common/buf.(*Buffer).BytesTo(...)
2022/09/15 22:53:34.631  [I] [io.go:428]        github.com/v2fly/v2ray-core/v4/common/buf/buffer.go:110
2022/09/15 22:53:34.631  [I] [io.go:428]  github.com/v2fly/v2ray-core/v4/common/crypto.(*AuthenticationReader).readBuffer(0x4000eb14a0, 0x7, 0x24)
2022/09/15 22:53:34.631  [I] [io.go:428]        github.com/v2fly/v2ray-core/v4/common/crypto/auth.go:140 +0x234
2022/09/15 22:53:34.631  [I] [io.go:428]  github.com/v2fly/v2ray-core/v4/common/crypto.(*AuthenticationReader).readInternal(0x4000eb14a0, 0x0, 0x400168bd20)
2022/09/15 22:53:34.631  [I] [io.go:428]        github.com/v2fly/v2ray-core/v4/common/crypto/auth.go:176 +0x168
2022/09/15 22:53:34.631  [I] [io.go:428]  github.com/v2fly/v2ray-core/v4/common/crypto.(*AuthenticationReader).ReadMultiBuffer(0x4000fbfa40?)
2022/09/15 22:53:34.631  [I] [io.go:428]        github.com/v2fly/v2ray-core/v4/common/crypto/auth.go:205 +0x54
2022/09/15 22:53:34.631  [I] [io.go:428]  github.com/v2fly/v2ray-core/v4/common/buf.copyInternal({0xafa7b8, 0x4000eb14a0}, {0xafbaf8, 0x4001134230}, 0x4000798570)
2022/09/15 22:53:34.631  [I] [io.go:428]        github.com/v2fly/v2ray-core/v4/common/buf/copy.go:81 +0x48
2022/09/15 22:53:34.631  [I] [io.go:428]  github.com/v2fly/v2ray-core/v4/common/buf.Copy({0xafa7b8, 0x4000eb14a0}, {0xafbaf8, 0x4001134230}, {0x400168bed8, 0x1, 0xafa798?})
2022/09/15 22:53:34.631  [I] [io.go:428]        github.com/v2fly/v2ray-core/v4/common/buf/copy.go:104 +0x94
2022/09/15 22:53:34.631  [I] [io.go:428]  github.com/v2fly/v2ray-core/v4/proxy/vmess/outbound.(*Handler).Process.func3()
2022/09/15 22:53:34.631  [I] [io.go:428]        github.com/v2fly/v2ray-core/v4/proxy/vmess/outbound/outbound.go:193 +0x2ec
2022/09/15 22:53:34.631  [I] [io.go:428]  github.com/v2fly/v2ray-core/v4/common/task.OnSuccess.func1()
2022/09/15 22:53:34.631  [I] [io.go:428]        github.com/v2fly/v2ray-core/v4/common/task/task.go:12 +0x30
2022/09/15 22:53:34.632  [I] [io.go:428]  github.com/v2fly/v2ray-core/v4/common/task.Run.func1
2022/09/15 22:53:34.632  [I] [io.go:428]  (0x40003e4300?)
2022/09/15 22:53:34.632  [I] [io.go:428]        github.com/v2fly/v2ray-core/v4/common/task/task.go:28 +0x38
2022/09/15 22:53:34.632  [I] [io.go:428]  created by github.com/v2fly/v2ray-core/v4/common/task.Run
2022/09/15 22:53:34.632  [I] [io.go:428]        github.com/v2fly/v2ray-core/v4/common/task/task.go:27
2022/09/15 22:53:34.632  [I] [io.go:428]   +0xd0

```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by mzz2017** [comment]
@malikshi What is your v2ray-core version?

**Comment by malikshi** [comment]
> @malikshi What is your v2ray-core version?

V2Ray 4.45.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.3 linux/arm64)
A unified platform for anti-censorship.

**Comment by mzz2017** [comment]
How can I reproduce it?

**Comment by malikshi** [comment]
> How can I reproduce it?

well, i don't know. i just running proxy load-balance with 4 vmess ws-cdn in it. i don't think it's RAM issues, or cpu issues.

**Comment by mzz2017** [comment]
@malikshi Is it stable to reproduce?

**Comment by malikshi** [comment]
> @malikshi Is it stable to reproduce?

yea? actually usually i am running v2rayA along xray without problem. and tyring to try v2ray-core and after 4 days running getting error like that. is it problem with v2ray-core or v2rayA?

**Comment by mzz2017** [comment]
@malikshi It seems v2ray-core's problem.

**Comment by malikshi** [comment]
ok!
maybe back to xray-core are good option for me.
Thanks you
