### ISSUE TITLE
管理页面点启动报错 无法启动

### ISSUE THREAD

**Issue by xuelongjiang** [v2rayA/v2rayA#848]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
docker 版 mzz2017 / v2rayA  最新下载安装
2. What approach of installation do you install V2rayA?
做路由
3. What is your operating system?
ubuntu 20.04

### Description

访问 http://ip:2017/ 管理页面 点左上角的 “就绪/启动”,返回：
failed to start v2ray-core: timeout: check the log for more information

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```
goroutine 199 [running]:
github.com/v2rayA/v2rayA/core/v2ray.NewProcess.func3()
	/build/service/core/v2ray/process.go:109 +0x67
created by github.com/v2rayA/v2rayA/core/v2ray.NewProcess
	/build/service/core/v2ray/process.go:107 +0x6ed
2023/03/15 09:16:17.547 [A] [main.go:26]  V2Ray binary is /usr/bin/v2ray
2023/03/15 09:16:17.547 [A] [main.go:26]  V2Ray asset directory is /run/user/0/v2raya
2023/03/15 09:16:17.547 [A] [main.go:26]  v2rayA working directory is /root
2023/03/15 09:16:17.547 [A] [main.go:26]  v2rayA configuration directory is /etc/v2raya
2023/03/15 09:16:17.547 [A] [main.go:26]  Golang: go1.19.4
2023/03/15 09:16:17.548 [A] [main.go:26]  OS: linux
2023/03/15 09:16:17.548 [A] [main.go:26]  Arch: amd64
2023/03/15 09:16:17.548 [A] [main.go:26]  Lite: false
2023/03/15 09:16:17.548 [A] [main.go:26]  Version: 2.0.1
2023/03/15 09:16:17.548 [A] [main.go:26]  Starting...
2023/03/15 09:16:17.548 [I] [main.go:27]  the core was not running the last time v2rayA exited
2023/03/15 09:16:17.637 [A] [index.go:116]  v2rayA is listening at http://127.0.0.1:2017
2023/03/15 09:16:17.638 [A] [index.go:116]  v2rayA is listening at http://192.168.1.237:2017
2023/03/15 09:16:17.638 [A] [index.go:116]  v2rayA is listening at http://192.168.122.1:2017
2023/03/15 09:16:17.638 [A] [index.go:116]  v2rayA is listening at http://172.17.0.1:2017
2023/03/15 09:16:17.638 [A] [index.go:116]  v2rayA is listening at http://[::1]:2017
2023/03/15 09:16:17.638 [A] [index.go:116]  v2rayA is listening at http://[fe80::d1aa:fa00:593:81bc]:2017
2023/03/15 09:16:17.638 [A] [index.go:116]  v2rayA is listening at http://[fe80::42:5eff:fed0:483f]:2017
Quitting...
2023/03/15 09:45:58.101 [A] [main.go:26]  V2Ray binary is /usr/bin/v2ray
2023/03/15 09:45:58.101 [A] [main.go:26]  V2Ray asset directory is /run/user/0/v2raya
2023/03/15 09:45:58.102 [A] [main.go:26]  v2rayA working directory is /root
2023/03/15 09:45:58.102 [A] [main.go:26]  v2rayA configuration directory is /etc/v2raya
2023/03/15 09:45:58.102 [A] [main.go:26]  Golang: go1.19.4
2023/03/15 09:45:58.102 [A] [main.go:26]  OS: linux
2023/03/15 09:45:58.102 [A] [main.go:26]  Arch: amd64
2023/03/15 09:45:58.102 [A] [main.go:26]  Lite: false
2023/03/15 09:45:58.102 [A] [main.go:26]  Version: 2.0.1
2023/03/15 09:45:58.102 [A] [main.go:26]  Starting...
2023/03/15 09:45:58.102 [I] [main.go:27]  the core was not running the last time v2rayA exited
2023/03/15 09:45:58.200 [A] [index.go:116]  v2rayA is listening at http://127.0.0.1:2017
2023/03/15 09:45:58.200 [A] [index.go:116]  v2rayA is listening at http://192.168.1.237:2017
2023/03/15 09:45:58.200 [A] [index.go:116]  v2rayA is listening at http://192.168.122.1:2017
2023/03/15 09:45:58.200 [A] [index.go:116]  v2rayA is listening at http://172.17.0.1:2017
2023/03/15 09:45:58.200 [A] [index.go:116]  v2rayA is listening at http://[::1]:2017
2023/03/15 09:45:58.200 [A] [index.go:116]  v2rayA is listening at http://[fe80::d1aa:fa00:593:81bc]:2017
2023/03/15 09:45:58.200 [A] [index.go:116]  v2rayA is listening at http://[fe80::42:5eff:fed0:483f]:2017
2023/03/15 09:46:21.797 [E] [version.go:36]  failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp 2.59.182.6:443: connect: connection refused
2023/03/15 09:46:33.984 [I] [io.go:429]  V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)
2023/03/15 09:46:33.985 [I] [io.go:429]  A unified platform for anti-censorship.
2023/03/15 09:46:49.568 [E] [connection.go:88]  failed to start v2ray-core: timeout: check the log for more information
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xbdda07]

goroutine 216 [running]:
github.com/v2rayA/v2rayA/core/v2ray.NewProcess.func3()
	/build/service/core/v2ray/process.go:109 +0x67
created by github.com/v2rayA/v2rayA/core/v2ray.NewProcess
	/build/service/core/v2ray/process.go:107 +0x6ed
2023/03/15 09:46:51.483 [A] [main.go:26]  V2Ray binary is /usr/bin/v2ray
2023/03/15 09:46:51.483 [A] [main.go:26]  V2Ray asset directory is /run/user/0/v2raya
2023/03/15 09:46:51.483 [A] [main.go:26]  v2rayA working directory is /root
2023/03/15 09:46:51.484 [A] [main.go:26]  v2rayA configuration directory is /etc/v2raya
2023/03/15 09:46:51.484 [A] [main.go:26]  Golang: go1.19.4
2023/03/15 09:46:51.484 [A] [main.go:26]  OS: linux
2023/03/15 09:46:51.484 [A] [main.go:26]  Arch: amd64
2023/03/15 09:46:51.484 [A] [main.go:26]  Lite: false
2023/03/15 09:46:51.484 [A] [main.go:26]  Version: 2.0.1
2023/03/15 09:46:51.484 [A] [main.go:26]  Starting...
2023/03/15 09:46:51.484 [I] [main.go:27]  the core was not running the last time v2rayA exited
2023/03/15 09:46:51.572 [A] [index.go:116]  v2rayA is listening at http://127.0.0.1:2017
2023/03/15 09:46:51.572 [A] [index.go:116]  v2rayA is listening at http://192.168.1.237:2017
2023/03/15 09:46:51.572 [A] [index.go:116]  v2rayA is listening at http://192.168.122.1:2017
2023/03/15 09:46:51.572 [A] [index.go:116]  v2rayA is listening at http://172.17.0.1:2017
2023/03/15 09:46:51.572 [A] [index.go:116]  v2rayA is listening at http://[::1]:2017
2023/03/15 09:46:51.572 [A] [index.go:116]  v2rayA is listening at http://[fe80::d1aa:fa00:593:81bc]:2017
2023/03/15 09:46:51.573 [A] [index.go:116]  v2rayA is listening at http://[fe80::42:5eff:fed0:483f]:2017

 You can also paste the log that comes from web administration page

```shell
# Paste running logs here



```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by xuelongjiang** [comment]
放了一个晚上，重启容器 故障消失了。
