### ISSUE TITLE
panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the devel go1.21-18e17e2cb1 Thu Jun 29 23:06:46 2023 +0000 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH="devel go1.21-18e17e2cb1 Thu Jun 29 23:06:46 2023 +0000" set. Notably, if devel go1.21-18e17e2cb1 Thu Jun 29 23:06:46 2023 +0000 adds a moving garbage collector, this program is unsafe to use.

### ISSUE THREAD

**Issue by NagatoException** [v2rayA/v2rayA#978]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.5
2. 你通过什么方式安装v2rayA
portage gentoo-zh overlay
3. 你所使用的操作系统
Gentoo Linux

### 描述问题
When i try to run v2raya, it report
```bash
panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the devel go1.21-18e17e2cb1 Thu Jun 29 23:06:46 2023 +0000 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH="devel go1.21-18e17e2cb1 Thu Jun 29 23:06:46 2023 +0000" set. Notably, if devel go1.21-18e17e2cb1 Thu Jun 29 23:06:46 2023 +0000 adds a moving garbage collector, this program is unsafe to use.

goroutine 1 [running]:
go4.org/unsafe/assume-no-moving-gc.init.0()
        /var/tmp/portage/net-proxy/v2rayA-9999/work/v2rayA-9999/service/vendor/go4.org/unsafe/assume-no-moving-gc/untested.go:25 +0x1da

```

### 复现问题的步骤
idk

### v2rayA/v2ray运行日志：

 ```bash
 v2raya
panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the devel go1.21-18e17e2cb1 Thu Jun 29 23:06:46 2023 +0000 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH="devel go1.21-18e17e2cb1 Thu Jun 29 23:06:46 2023 +0000" set. Notably, if devel go1.21-18e17e2cb1 Thu Jun 29 23:06:46 2023 +0000 adds a moving garbage collector, this program is unsafe to use.

goroutine 1 [running]:
go4.org/unsafe/assume-no-moving-gc.init.0()
        /var/tmp/portage/net-proxy/v2rayA-9999/work/v2rayA-9999/service/vendor/go4.org/unsafe/assume-no-moving-gc/untested.go:25 +0x1da
```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by CAIMEOX** [comment]
Maybe you can solve it by yourself.
- You can try to update the module yourself (`go get -u go4.org/unsafe/assume-no-moving-gc`) if you can.
- If you are sure what are you doing and you cant update the module above, you can set the environment variable `ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH="devel go1.21-18e17e2cb1 Thu Jun 29 23:06:46 2023 +0000"` as the message says
